GemeenteNijmegen/mijn-services

src/Configuration.ts
=> chore: switch branch name production -> main

src/Configuration.ts
=> feat: use consistent domain names

src/Configuration.ts, src/MainStack.ts, src/MijnServicesStage.ts, src/PipelineStack.ts, src/constructs/DnsRecords.ts
=> feat: add cname records and refactored stage/stack names

src/MainStack.ts, src/constructs/Redis.ts
=> feat: redis cache database

src/Configuration.ts, src/DatabaseStack.ts, src/MainStack.ts, src/ParameterStage.ts, src/Statics.ts, src/Utils.ts, src/constructs/Redis.ts, src/constructs/ServiceFactory.ts, src/custom-resources/create-databases/create-databases.lambda.ts, src/services/OpenKlant.ts, src/services/OpenNotificaties.ts, src/services/OpenZaak.ts
- Solved security hub findings (read-only root file system & automatic backup cache db)
- Deploy OpenNotificaties in acceptance environment (incl. rabbit MQ)
- Deploy OpenZaak in acceptance environment
=> feat: open notificaties & open klant in acceptance

src/Configuration.ts
Related to https://github.com/GemeenteNijmegen/mijn-services/issues/26
=> feat: deploy open klant registration service endpoin woweb in production

src/Configuration.ts, src/services/OpenKlantRegistrationService/NotificationReceiver/receiver.lambda.ts, src/services/OpenKlantRegistrationService/OpenKlantRegistrationService.ts
=> chore: add enabled feature flag for OpenKlantRegistrationService

src/Utils.ts
=> chore: fix toPythonBooleanString logic

src/Statics.ts, test/utils.test.ts
- Create database for open-zaak en open-notificaties
- test utils class
=> feat: create open-zaak en open-notifications database (+tests)

src/services/OpenZaak.ts, test/utils.test.ts
=> feat: enable write to root fs for open-zaak

src/Configuration.ts, src/MainStack.ts, src/ParameterStage.ts, src/Statics.ts, src/Utils.ts, src/services/Objects.ts, src/services/Objecttypes.ts, src/services/OpenZaak.ts, test/utils.test.ts
- Add services for objecttypes and objects api
- Including database creation
- Celery container for objects api is WIP
=> feat: objecttypes and objects api

package.json, src/services/Objects.ts, src/services/OpenKlant.ts, src/services/OpenNotificaties.ts, src/services/OpenZaak.ts, yarn.lock
- fixed typos
- Write celery health check results to logs
- Update celery health checks
=> chore: update celery health check to write to logs

package.json, src/Configuration.ts, src/MainStack.ts, src/constructs/Database.ts, src/services/OpenKlantRegistrationService/OpenKlantRegistrationService.ts, src/services/OpenKlantRegistrationService/RegistrationHandler/OpenKlantRegistrationHandler.ts, src/services/OpenKlantRegistrationService/RegistrationHandler/registration-handler.lambda.ts, src/services/OpenKlantRegistrationService/RegistrationHandler/strategies/PartijPerRolStrategy.ts, src/services/OutputManagementComponent.ts, yarn.lock
Fixes #https://github.com/GemeenteNijmegen/open-forms/issues/143
=> feat: rds backup plan & catalogi whitelist for open-klant vul service

src/Configuration.ts
=> feat: add woweb production omc

package.json, src/Configuration.ts, src/constructs/Database.ts, yarn.lock
Setup production omc for woweb:
- Template IDs are filled and correct
- Objects API does not yet exist but expected on this urls
- Connectivity & configuration for notify can be setup
=> feat: setup woweb production omc 

src/constructs/Database.ts
Fixes kms key for the backup vault
=> feat: add kms key for the backup vault

src/constructs/Database.ts
=> chore: temp remove backup vault

src/constructs/Database.ts
=> feat: retry backup plan

src/custom-resources/create-databases/create-databases.lambda.ts
=> feat: create user client for each db

src/custom-resources/create-databases/create-databases.lambda.ts
Revert changes create db lambda
=> chore: revert changes create db lambda

src/services/OpenKlantRegistrationService/RegistrationHandler/ZakenApi.ts
=> feat: only panic when rol is deleted

src/services/OpenKlantRegistrationService/RegistrationHandler/strategies/PartijPerRolStrategyWithForm.ts
do not fail while retreiving submission
=> chore: do not fail while retreiving submission

src/Configuration.ts, src/MainStack.ts, src/ParameterStage.ts, src/Statics.ts, src/services/OpenProduct/OpenProduct.ts, src/services/OpenProduct/README.md
=> feat: basic setup of open product containers with feature flag acc only

src/constructs/CloudfrontDistributionForLoadBalancer.ts
=> chore: make sure cloudfront distribution exists before obtaining sg

src/Configuration.ts, src/ConfigurationInterfaces.ts, src/MainStack.ts, src/constructs/ContainerPlatform.ts
=> feat: feature flag for gradual deployment

src/Configuration.ts
=> feat: update OMC to latest version

src/services/OutputManagementComponent.ts
=> chore: path rewrite in api gateway not required anymore

src/MainStack.ts, src/Statics.ts, src/constructs/CloudfrontDistributionForLoadBalancer.ts, src/constructs/ContainerPlatform.ts, src/constructs/LoadBalancer.ts, src/services/OpenKlantRegistrationService/OpenKlantRegistrationService.ts, src/services/OutputManagementComponent.ts
- Added open-klant-vul-service to exposed services
- Configure cloudfront behaviour for forwarding headers, querystrings and cookies.
=> feat: cloudfront config and extra services

src/constructs/CloudfrontDistributionForLoadBalancer.ts
=> chore: deploy https vpc origin (attempt 2)

src/Configuration.ts
=> feat: deploy loadbalancer migration records prod
